data:extend{
    {
        type = "technology",
        name = "mortar-turret-damage-1",
        icons = util.technology_icon_constant_damage("__strategy-mortar-turret__/graphics/technology/mortar-turret.png"),
        effects = {
            {type = "turret-attack", turret_id = "mortar-turret", modifier = 0.2},
            {type = "turret-attack", turret_id = "tilted-mortar-turret", modifier = 0.2},
        },
        prerequisites = { "mortar-turret" },
        upgrade = true,
        order = "z",
        unit = {
            count = 200,
            ingredients = {
                { "automation-science-pack", 1 },
                { "logistic-science-pack",   1 },
                { "military-science-pack",   1 },
            },
            time = 30,
        },
    },
    {
        type = "technology",
        name = "mortar-turret-damage-2",
        icons = util.technology_icon_constant_damage("__strategy-mortar-turret__/graphics/technology/mortar-turret.png"),
        effects = {
            {type = "turret-attack", turret_id = "mortar-turret", modifier = 0.2},
            {type = "turret-attack", turret_id = "tilted-mortar-turret", modifier = 0.2},
        },
        prerequisites = { "chemical-science-pack", "mortar-turret-damage-1" },
        upgrade = true,
        order = "z",
        unit = {
            count = 300,
            ingredients = {
                { "automation-science-pack", 1 },
                { "logistic-science-pack",   1 },
                { "military-science-pack",   1 },
                { "chemical-science-pack",   1 },
            },
            time = 60,
        },
    },
    {
        type = "technology",
        name = "mortar-turret-damage-3",
        icons = util.technology_icon_constant_damage("__strategy-mortar-turret__/graphics/technology/mortar-turret.png"),
        effects = {
            {type = "turret-attack", turret_id = "mortar-turret", modifier = 0.2},
            {type = "turret-attack", turret_id = "tilted-mortar-turret", modifier = 0.2},
            {type = "turret-attack", turret_id = "heavy-mortar-turret", modifier = 0.2},
            {type = "turret-attack", turret_id = "tilted-heavy-mortar-turret", modifier = 0.2},
        },
        prerequisites = { "utility-science-pack", "mortar-turret-damage-2" },
        upgrade = true,
        order = "z",
        unit = {
            count = 400,
            ingredients = {
                { "automation-science-pack", 1 },
                { "logistic-science-pack",   1 },
                { "military-science-pack",   1 },
                { "chemical-science-pack",   1 },
                { "utility-science-pack",    1 },
            },
            time = 60,
        },
    },
    {
        type = "technology",
        name = "mortar-turret-damage-4",
        icons = util.technology_icon_constant_damage("__strategy-mortar-turret__/graphics/technology/mortar-turret.png"),
        effects = {
            {type = "turret-attack", turret_id = "mortar-turret", modifier = 0.2},
            {type = "turret-attack", turret_id = "tilted-mortar-turret", modifier = 0.2},
            {type = "turret-attack", turret_id = "heavy-mortar-turret", modifier = 0.2},
            {type = "turret-attack", turret_id = "tilted-heavy-mortar-turret", modifier = 0.2},
        },
        prerequisites = { "space-science-pack", "mortar-turret-damage-3" },
        max_level = "infinite",
        upgrade = true,
        order = "z",
        unit = {
            count_formula = "2^(L-4)*500",
            ingredients = {
                { "automation-science-pack", 1 },
                { "logistic-science-pack",   1 },
                { "military-science-pack",   1 },
                { "chemical-science-pack",   1 },
                { "utility-science-pack",    1 },
                { "space-science-pack",      1 },
            },
            time = 60,
        },
    },
}